### ISSUE TITLE
How can I run this?

### ISSUE THREAD

**Issue by aayush-g1414** [5elfle5/coinflip-bet#2]
Is there a way to run this on Vercel or something? Or through commands?

**Comment by 5elfle5** [comment]
I recommend to run it on Linux or Mac OS, it was not too hard to install environment on Manjaro Linux, on a Mac with M1 i had to use Rosetta, there was a tutorial somewhere
Pre-requisites: install rust, solana cli, anchor cli, create solana wallet, set solana cluster to 127.0.0.1:8899, airdrop some SOLs, install Phantom Wallet in your browser, send some SOLs there
1. Hard reset to "fixed deprecated method commit"
2. go to Anchor.toml, set correct "wallet" variable (set path to json of your wallet)
3. in root directory "cargo build", "yarn install", "anchor build"
4. in coinflip-fe directory "yarn install", "yarn build"
5. in any directory "solana-test-validator"
6. in root directory "anchor deploy"
7. find and replace in project program id (can be found in Anchor.toml, field coinflip_bet) with the one that anchor deploy created
8. anchor deploy again
9. in coinflip-fe "yarn start"
10. open localhost:1234, there will be log in with Phantom wallet and 2 stupid button, you can click left one and then the right one

What this did: it ran a smart contract and then read the account with the newly set data. But this is super primitive thing. This project is in very early stage, and I don't know if I will work on it, because I will be working on a job from Aug 22nd.

My next plans were:
1. add ability to transfer SOLs withint the smart contract
2. add animation of coinflip, together with choosing amount of money to bet, and a side to bet on
3. start coinflip animation together with calling a smart contract and then reading the account for results, when results are known stop the animation with a given result.

Account will just tell you if you won of lost. Probability to win will be 48%.
But, I believe that the smart contract is actually not secure, so my final step was supposed to be implement the hack that will allow to win every time

(this was written from memory, there might be step missing, or something)

**Comment by TamTamJov** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings. 

Please email me @ tameehvh@gmail.com or send me a message on Discord - Jovan#6064 if you'd like more information. 

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.

**Comment by neonflux-io** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings.

Please send me a message on Discord - bounsert if you'd like more information.

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.

**Comment by neonflux-io** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings.

Please send me a message on Discord - bounsert if you'd like more information.

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.

**Comment by neonflux-io** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings.

Please send me a message on Discord - bounsert if you'd like more information.

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.

**Comment by neonflux-io** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings.

Please send me a message on Discord - bounsert if you'd like more information.

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.

**Comment by neonflux-io** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings.

Please send me a message on Discord - bounsert if you'd like more information.

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.

**Comment by neonflux-io** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings.

Please send me a message on Discord - bounsert if you'd like more information.

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.

**Comment by neonflux-io** [comment]
Hi 5elfle5

I'm a founder of a NFT collection that sold out based on RPC utility. We're looking for someone who can Dev a Solana Coinflip for 5 - 6 digit earnings.

Please send me a message on Discord - bounsert if you'd like more information.

We're going to start another NFT collection soon, and we need Solana Rust developers to be apart of our project. A lot of money to be made.
